apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-tcp
  name: frontend-tcp
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 80
  selector:
    io.kompose.service: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
