version: 0.2

env:
  variables:
     ECR_REPO_NAME: "hello-world-nodejs-repo"
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"      
  pre_build:
    commands:
      - echo aws login
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 111111111111.dkr.ecr.ca-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - IMAGE_TAG=`echo $CODEBUILD_BUILD_NUMBER`
      - echo Building the Docker image...          
      - docker build -t $APP_NAME:$IMAGE_TAG .
      - docker run -d --name $APP_NAME -p 5000:5000 $APP_NAME:$IMAGE_TAG
      - docker logs $APP_NAME
      - curl http://localhost:5000
      - docker tag $APP_NAME:$IMAGE_TAG 111111111111.dkr.ecr.ca-central-1.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 111111111111.dkr.ecr.ca-central-1.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - echo Stop and remove container and images
      - docker stop $APP_NAME
      - docker rm $APP_NAME
      - docker rmi 111111111111.dkr.ecr.ca-central-1.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - docker rmi $APP_NAME:$IMAGE_TAG